// This file is generated by `scripts/create-ts-compiler-api.mjs`. DO NOT edit manually.

import { CompilerPackageNames, CompilerVersions } from "./versions";

export async function importCompilerAPI(packageName: CompilerPackageNames) {
  switch (packageName) {
    case "typescript":
      return await import("typescript");
    default:
      throw new Error(`no valid version in package: ${packageName}`);
  }
}

export async function importLibFiles(packageName: CompilerPackageNames) {
  switch (packageName) {
    case "typescript":
      return await import("../libFiles/typescript/index.js");
    default:
      throw new Error(`no valid version in package: ${packageName}`);
  }
}
