// This file is generated by `scripts/create-ts-compiler-api.mjs`. DO NOT edit manually.

export type CompilerPackageNames = "typescript";
export type CompilerVersions = "5.0.2";
export const compilerVersionCollection: {
  version: CompilerVersions;
  packageName: CompilerPackageNames;
}[] = [{ version: "5.0.2", packageName: "typescript" }];
