import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Encre Concepts",
      items: [
        {
          type: "doc",
          id: "ConceptsOverview",  // Refers to ConceptsOverview.md
        },
        {
          type: "category",
          label: "Serializable",
          items: [
            {
              type: "doc",
              id: "ConeptsOverview/Serializable/Serializable",  
            // {
            //   type: "autogenerated",
            //   dirName: "ConceptsOverview/Serializable",  // Includes other docs in the Serializable directory
            }
          ], 
        },
        {
          type: "category",
          label: "Callable",
          items: [
            {
              type: "doc",
              id: "ConeptsOverview/Callable/Callable",  
            // {
            //   type: "autogenerated",
            //   dirName: "ConceptsOverview/Serializable",  // Includes other docs in the Serializable directory
            }
          ], 
        },
        {
          type: "category",
          label: "Events",
          items: [
            {
              type: "doc",
              id: "ConeptsOverview/Events/Events",  
            // {
            //   type: "autogenerated",
            //   dirName: "ConceptsOverview/Serializable",  // Includes other docs in the Serializable directory
            }
          ], 
        },
      ],
    },
    {
      API: [
        {
          type: "category",
          label: "Encre Core",
          link: {
            type: "doc",
            id: "api/core/modules",
          },
          items: [
            {
              Cache: [
                {
                  type: "autogenerated",
                  dirName: "api/core/cache",
                },
              ],
              Events: [
                {
                  type: "autogenerated",
                  dirName: "api/core/events",
                },
              ],
              Load: [
                {
                  type: "autogenerated",
                  dirName: "api/core/load",
                },
              ],
              Record: [
                {
                  type: "autogenerated",
                  dirName: "api/core/record",
                },
              ],
              Studio: [
                {
                  type: "autogenerated",
                  dirName: "api/core/studio",
                },
              ],
              Utils: [
                {
                  type: "autogenerated",
                  dirName: "api/core/utils",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
