import { atom } from 'recoil';

import { Guardrail } from '../types/studio.type';

export const selectingGuardrailIdsState = atom<string[]>({
  key: 'selectingGuardrailIdsState',
  default: [],
});

// TODO: get this from core
export const registeredGuardrailsState = atom<{ [key in string]: Guardrail }>({
  key: 'registeredGuardrailsState',
  default: {
    'array-contains': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'contains {{value}}',
      id: 'z5ak9StsnAIXiUHvB',
      name: 'contains',
      type: 'array',
    },
    'array-doesNotContain': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'does not contain {{value}}',
      id: '5uHi8DSwoxG1xFsKz',
      name: 'doesNotContain',
      type: 'array',
    },
    'array-doesNotExist': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'does not exist',
      id: '7LKivTspiPl06z_Gy',
      name: 'doesNotExist',
      type: 'array',
    },
    'array-exists': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'exists',
      id: '35sNEn7hk_vUKy4KK',
      name: 'exists',
      type: 'array',
    },
    'array-isNotStrictlyEqual': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'is not equal to {{value}}',
      id: '3DHRiuSeWNG6vqx2b',
      name: 'isNotStrictlyEqual',
      type: 'array',
    },
    'array-isStrictlyEqual': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'is equal to {{value}}',
      id: 'lxACxtK1WPp8ml9VP',
      name: 'isStrictlyEqual',
      type: 'array',
    },
    'array-lengthEqual': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'length equal to {{value}}',
      id: 'U81OeFIDFSRrwMFcC',
      name: 'lengthEqual',
      type: 'array',
    },
    'array-lengthGreaterThan': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'length greater than {{value}}',
      id: 'cOGvAxEY2r9r3VmrW',
      name: 'lengthGreaterThan',
      type: 'array',
    },
    'array-lengthGreaterThanOrEqual': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'length greater than or equal {{value}}',
      id: 'CB_jw0RpRZEUT8nqp',
      name: 'lengthGreaterThanOrEqual',
      type: 'array',
    },
    'array-lengthLessThan': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'length less than {{value}}',
      id: 'YK70HIFKISvnu4l50',
      name: 'lengthLessThan',
      type: 'array',
    },
    'array-lengthLessThanOrEqual': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'length less than or equal {{value}}',
      id: 'Et5GMhmy4l4z4eGj1',
      name: 'lengthLessThanOrEqual',
      type: 'array',
    },
    'array-lengthNotEqual': {
      dataType: [
        'string[]',
        'number[]',
        'boolean[]',
        'unknown[]',
        'object[]',
        'blob[]',
      ],
      detail: 'length not equal to {{value}}',
      id: 'IeBDbJHnCFrb@2i8G',
      name: 'lengthNotEqual',
      type: 'array',
    },
    'boolean-doesNotExist': {
      dataType: ['boolean', 'unknown'],
      detail: 'does not exist',
      id: '_Rw3ILTwknSt8@Ju7',
      name: 'doesNotExist',
      type: 'boolean',
    },
    'boolean-exists': {
      dataType: ['boolean', 'unknown'],
      detail: 'exists',
      id: 'QCa3HIyRTpFZgO59p',
      name: 'exists',
      type: 'boolean',
    },
    'boolean-isEqual': {
      dataType: ['boolean', 'unknown'],
      detail: 'is equal to {{value}}',
      id: 'LS@rQCMFIGmDL_Dqf',
      name: 'isEqual',
      type: 'boolean',
    },
    'boolean-isFalse': {
      dataType: ['boolean', 'unknown'],
      detail: 'is false',
      id: 'QfSkMxQvORfsLKibe',
      name: 'isFalse',
      type: 'boolean',
    },
    'boolean-isNotEqual': {
      dataType: ['boolean', 'unknown'],
      detail: 'is not equal to {{value}}',
      id: '97WOmSR5C1yj2xaQI',
      name: 'isNotEqual',
      type: 'boolean',
    },
    'boolean-isTrue': {
      dataType: ['boolean', 'unknown'],
      detail: 'is true',
      id: 'Abr1T4u3uGJfCD@aw',
      name: 'isTrue',
      type: 'boolean',
    },
    'number-doesNotExist': {
      dataType: ['number', 'unknown'],
      detail: 'does not exist',
      id: '4zdIpHUCYna4wPnjx',
      name: 'doesNotExist',
      type: 'number',
    },
    'number-exists': {
      dataType: ['number', 'unknown'],
      detail: 'exists',
      id: 'xEH4ssgSGcsO_Uaeg',
      name: 'exists',
      type: 'number',
    },
    'number-isEqual': {
      dataType: ['number', 'unknown'],
      detail: 'is equal to {{value}}',
      id: 'G14@f0qatW@@dsYXY',
      name: 'isEqual',
      type: 'number',
    },
    'number-isGreaterThan': {
      dataType: ['number', 'unknown'],
      detail: 'is greater than {{value}}',
      id: 'EkZ_tkZFM1hrrJEDI',
      name: 'isGreaterThan',
      type: 'number',
    },
    'number-isGreaterThanOrEqual': {
      dataType: ['number', 'unknown'],
      detail: 'is greater than or equal {{value}}',
      id: '7QT3bSgCzc9xazL5u',
      name: 'isGreaterThanOrEqual',
      type: 'number',
    },
    'number-isLessThan': {
      dataType: ['number', 'unknown'],
      detail: 'is less than {{value}}',
      id: 'TmAA5FfGRpinPRMmt',
      name: 'isLessThan',
      type: 'number',
    },
    'number-isLessThanOrEqual': {
      dataType: ['number', 'unknown'],
      detail: 'is less than or equal {{value}}',
      id: '4pFGeLV@w0DpI34a8',
      name: 'isLessThanOrEqual',
      type: 'number',
    },
    'number-isNotEqual': {
      dataType: ['number', 'unknown'],
      detail: 'is not equal to {{value}}',
      id: 'UliSPoTTOOS@YAXZl',
      name: 'isNotEqual',
      type: 'number',
    },
    'object-doesNotExist': {
      dataType: ['object', 'unknown'],
      detail: 'does not exist',
      id: 'v7K4U9YJXeCelkuvv',
      name: 'doesNotExist',
      type: 'object',
    },
    'object-exists': {
      dataType: ['object', 'unknown'],
      detail: 'exists',
      id: 'Bv6p125JvQrp6sl3c',
      name: 'exists',
      type: 'object',
    },
    'object-isEmpty': {
      dataType: ['object', 'unknown'],
      detail: 'is empty',
      id: 'HaKx@@hnPsTMRmpCi',
      name: 'isEmpty',
      type: 'object',
    },
    'object-isNotEmpty': {
      dataType: ['object', 'unknown'],
      detail: 'is not empty',
      id: 'UzYOrSc1viCnw3pzg',
      name: 'isNotEmpty',
      type: 'object',
    },
    'object-isNotStrictlyEqual': {
      dataType: ['object', 'unknown'],
      detail: 'is not equal to {{value}}',
      id: '2iAlgEmlk1ehlhilU',
      name: 'isNotStrictlyEqual',
      type: 'object',
    },
    'object-isStrictlyEqual': {
      dataType: ['object', 'unknown'],
      detail: 'is equal to {{value}}',
      id: 'iNXxXWqgvifTGLS0F',
      name: 'isStrictlyEqual',
      type: 'object',
    },
    'string-contains': {
      dataType: ['string', 'unknown'],
      detail: 'contains {{value}}',
      id: 'aciJc1kZA3wdpvCNX',
      name: 'contains',
      type: 'string',
    },
    'string-doesNotContain': {
      dataType: ['string', 'unknown'],
      detail: 'does not contain {{value}}',
      id: 'koZvyuWv9dXdKLSSZ',
      name: 'doesNotContain',
      type: 'string',
    },
    'string-doesNotEndWith': {
      dataType: ['string', 'unknown'],
      detail: 'does not end with {{value}}',
      id: 'r4X4NCRtmv_444sWz',
      name: 'doesNotEndWith',
      type: 'string',
    },
    'string-doesNotExist': {
      dataType: ['string', 'unknown'],
      detail: 'does not exist',
      id: 'kf19ag55EmJiUgscU',
      name: 'doesNotExist',
      type: 'string',
    },
    'string-doesNotMatchRegex': {
      dataType: ['string', 'unknown'],
      detail: 'does not match regex {{regex}}',
      id: 'ujdKAaiyKU4CCEAuc',
      name: 'doesNotMatchRegex',
      type: 'string',
    },
    'string-doesNotStartWith': {
      dataType: ['string', 'unknown'],
      detail: 'does not start with {{value}}',
      id: 'VkkNiRGojlI_Dp_Kc',
      name: 'doesNotStartWith',
      type: 'string',
    },
    'string-endsWith': {
      dataType: ['string', 'unknown'],
      detail: 'ends with {{value}}',
      id: '3x@JKfLAK5vZ38TSB',
      name: 'endsWith',
      type: 'string',
    },
    'string-exists': {
      dataType: ['string', 'unknown'],
      detail: 'exists',
      id: 'wZ_kbWIrw7mMjedUw',
      name: 'exists',
      type: 'string',
    },
    'string-isEqual': {
      dataType: ['string', 'unknown'],
      detail: 'is equal to {{value}}',
      id: '40v5DKha0qHeKGPMT',
      name: 'isEqual',
      type: 'string',
    },
    'string-isNotEqual': {
      dataType: ['string', 'unknown'],
      detail: 'is not equal to {{value}}',
      id: 'MozjvFvMNAANp09LO',
      name: 'isNotEqual',
      type: 'string',
    },
    'string-lengthEqual': {
      dataType: ['string', 'unknown'],
      detail: 'length equal to {{value}}',
      id: 'J@eVoCRa_w1yT2iTj',
      name: 'lengthEqual',
      type: 'string',
    },
    'string-lengthGreaterThan': {
      dataType: ['string', 'unknown'],
      detail: 'length greater than {{value}}',
      id: 'cZLaVi02U42vRO8z_',
      name: 'lengthGreaterThan',
      type: 'string',
    },
    'string-lengthGreaterThanOrEqual': {
      dataType: ['string', 'unknown'],
      detail: 'length greater than or equal {{value}}',
      id: '3u6BWwaR0BSO6vSN7',
      name: 'lengthGreaterThanOrEqual',
      type: 'string',
    },
    'string-lengthLessThan': {
      dataType: ['string', 'unknown'],
      detail: 'length less than {{value}}',
      id: 'VcPtSpdNq8VvJqxWF',
      name: 'lengthLessThan',
      type: 'string',
    },
    'string-lengthLessThanOrEqual': {
      dataType: ['string', 'unknown'],
      detail: 'length less than or equal {{value}}',
      id: '8IxAddzRZk_KxvYdK',
      name: 'lengthLessThanOrEqual',
      type: 'string',
    },
    'string-lengthNotEqual': {
      dataType: ['string', 'unknown'],
      detail: 'length not equal to {{value}}',
      id: 'CoJGPlgnFf76Js@ai',
      name: 'lengthNotEqual',
      type: 'string',
    },
    'string-matchesRegex': {
      dataType: ['string', 'unknown'],
      detail: 'matches regex {{regex}}',
      id: '1ldqjj0SpEp7c_aRd',
      name: 'matchesRegex',
      type: 'string',
    },
    'string-startsWith': {
      dataType: ['string', 'unknown'],
      detail: 'starts with {{value}}',
      id: 'fLTkidlggTV4UnenR',
      name: 'startsWith',
      type: 'string',
    },
  },
});
