export const ENCRE_DATA_TYPES = [
  "string",
  "string[]",
  "number",
  "number[]",
  "boolean",
  "boolean[]",
  "unknown",
  "unknown[]",
  "object",
  "object[]",
  "blob",
  "blob[]",
  "context",
  "context[]",
  "chat-message",
  "chat-message[]",
];

export const EXT_MAP = {
  "text/plain": "bin",
  "text/html": "html",
  "text/javascript": "js",
  "text/css": "css",
  "application/json": "json",
  "application/pdf": "pdf",
  "application/xml": "xml",
  "image/png": "png",
  "image/jpeg": "jpeg",
  "image/gif": "gif",
  "image/svg+xml": "svg",
  "audio/mp3": "mp3",
  "audio/ogg": "ogg",
  "audio/wav": "wav",
};
