// This file is generated by `scripts/create-entrypoints.js`. DO NOT edit manually.

export const optionalImportEndpoints = [
  'events/input/load/docs/pdf',
  'events/input/load/msgs/bot',
  'events/input/load/msgs/human',
  'events/input/load/msgs/system',
  'events/input/load/msgs/function',
  'events/input/load/msgs/general',
  'events/input/load/prompts/text',
  'events/input/load/prompts/chat',
  'events/input/transform/splitter',
  'events/inference/validate/guardrails/array',
  'events/inference/validate/guardrails/boolean',
  'events/inference/validate/guardrails/object',
  'events/inference/validate/guardrails/number',
  'events/inference/validate/guardrails/string',
  'events/inference/validate/validator',
  'events/inference/chat/llms/openai',
  'events/inference/chat/chatlms/openai',
  'events/inference/chat/llms/gemini',
  'events/inference/chat/chatlms/gemini',
  'studio/graph'
] as string[];
