// This file is generated by `scripts/create-entrypoints.js`. DO NOT edit manually.

export interface OptionalImportMap {
  'events/embeddings/openai'?:
    | typeof import('./events/embeddings/openai.js')
    | Promise<typeof import('./events/embeddings/openai.js')>;
  'events/input/load/docs/pdf'?:
    | typeof import('./events/input/load/docs/pdf.js')
    | Promise<typeof import('./events/input/load/docs/pdf.js')>;
  'events/input/load/msgs/bot'?:
    | typeof import('./events/input/load/msgs/bot.js')
    | Promise<typeof import('./events/input/load/msgs/bot.js')>;
  'events/input/load/msgs/human'?:
    | typeof import('./events/input/load/msgs/human.js')
    | Promise<typeof import('./events/input/load/msgs/human.js')>;
  'events/input/load/msgs/system'?:
    | typeof import('./events/input/load/msgs/system.js')
    | Promise<typeof import('./events/input/load/msgs/system.js')>;
  'events/input/load/msgs/function'?:
    | typeof import('./events/input/load/msgs/function.js')
    | Promise<typeof import('./events/input/load/msgs/function.js')>;
  'events/input/load/msgs/general'?:
    | typeof import('./events/input/load/msgs/chat.js')
    | Promise<typeof import('./events/input/load/msgs/chat.js')>;
  'events/input/load/prompts/text'?:
    | typeof import('./events/input/load/prompts/text.js')
    | Promise<typeof import('./events/input/load/prompts/text.js')>;
  'events/input/load/prompts/chat'?:
    | typeof import('./events/input/load/prompts/chat.js')
    | Promise<typeof import('./events/input/load/prompts/chat.js')>;
  'events/input/load/rules'?:
    | typeof import('./events/input/load/rules/base.js')
    | Promise<typeof import('./events/input/load/rules/base.js')>;
  'events/input/load/vectorstore/chroma'?:
    | typeof import('./events/input/load/vectorstore/chroma.js')
    | Promise<typeof import('./events/input/load/vectorstore/chroma.js')>;
  'events/input/transform/splitter'?:
    | typeof import('./events/input/transform/splitter.js')
    | Promise<typeof import('./events/input/transform/splitter.js')>;
  'events/inference/validate/guardrails/array'?:
    | typeof import('./events/inference/validate/guardrails/array.js')
    | Promise<typeof import('./events/inference/validate/guardrails/array.js')>;
  'events/inference/validate/guardrails/boolean'?:
    | typeof import('./events/inference/validate/guardrails/boolean.js')
    | Promise<typeof import('./events/inference/validate/guardrails/boolean.js')>;
  'events/inference/validate/guardrails/object'?:
    | typeof import('./events/inference/validate/guardrails/object.js')
    | Promise<typeof import('./events/inference/validate/guardrails/object.js')>;
  'events/inference/validate/guardrails/number'?:
    | typeof import('./events/inference/validate/guardrails/number.js')
    | Promise<typeof import('./events/inference/validate/guardrails/number.js')>;
  'events/inference/validate/guardrails/string'?:
    | typeof import('./events/inference/validate/guardrails/string.js')
    | Promise<typeof import('./events/inference/validate/guardrails/string.js')>;
  'events/inference/validate/validator'?:
    | typeof import('./events/inference/validate/validators/variable.js')
    | Promise<typeof import('./events/inference/validate/validators/variable.js')>;
  'events/inference/chat/llms/openai'?:
    | typeof import('./events/inference/chat/llms/openai/text.js')
    | Promise<typeof import('./events/inference/chat/llms/openai/text.js')>;
  'events/inference/chat/chatlms/openai'?:
    | typeof import('./events/inference/chat/llms/openai/chat.js')
    | Promise<typeof import('./events/inference/chat/llms/openai/chat.js')>;
  'events/inference/chat/llms/gemini'?:
    | typeof import('./events/inference/chat/llms/vertexai/gemini/text.js')
    | Promise<typeof import('./events/inference/chat/llms/vertexai/gemini/text.js')>;
  'events/inference/chat/chatlms/gemini'?:
    | typeof import('./events/inference/chat/llms/vertexai/gemini/chat.js')
    | Promise<typeof import('./events/inference/chat/llms/vertexai/gemini/chat.js')>;
  'events/inference/retrieve/embedding/vectorstore'?:
    | typeof import('./events/inference/retrieve/embedding/vectorstore.js')
    | Promise<typeof import('./events/inference/retrieve/embedding/vectorstore.js')>;
  'studio/condition'?:
    | typeof import('./studio/condition.js')
    | Promise<typeof import('./studio/condition.js')>;
  'studio/graph'?:
    | typeof import('./studio/graph.js')
    | Promise<typeof import('./studio/graph.js')>;
  'studio/input'?:
    | typeof import('./studio/input.js')
    | Promise<typeof import('./studio/input.js')>;
}

export interface SecretMap {
  GOOGLE_API_KEY?: string;
  OPENAI_API_KEY?: string;
  OPENAI_ORGANIZATION?: string;
  REMOTE_RETRIEVER_AUTH_BEARER?: string;
}