// This file is generated by `scripts/create-entrypoints.js`. DO NOT edit manually.

export const optionalImportEndpoints = [
  'record/callable',
  'cache',
  'cache/base',
  'events/input/load/docs/base',
  'events/input/load/docs/buffer',
  'events/input/load/docs/pdf',
  'events/input/load/msgs/base',
  'events/input/load/prompts/base',
  'events/input/load/prompts/chat',
  'events/output/provide/base',
  'events/output/provide/file',
  'events/output/provide/llmresult',
  'events/output/provide/message'
] as string[];
