// This file is generated by `scripts/create-entrypoints.js`. DO NOT edit manually.

export const optionalImportEndpoints = [
  'events/input/load/docs/buffer',
  'events/input/load/docs/pdf'
] as string[];
