// This file is generated by `scripts/create-entrypoints.js`. DO NOT edit manually.

export interface OptionalImportMap {
  'events/input/load/docs/buffer'?:
    | typeof import('./events/input/load/docs/buffer.js')
    | Promise<typeof import('./events/input/load/docs/buffer.js')>;
  'events/input/load/docs/pdf'?:
    | typeof import('./events/input/load/docs/pdf.js')
    | Promise<typeof import('./events/input/load/docs/pdf.js')>;
}

export interface SecretMap {

}